version: "3.7"
services:
 db:
  image: postgres
  environment:
   - POSTGRES_DB=postgres
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=12qwaszx
  ports:
   - 5432:5432
 java-db-app:
  build: .
  volumes:
    - ../target/products.war:/usr/local/tomcat/webapps/ROOT.war
  ports:
   - 8080:8080
  links:
   - db